name: Test, Build, and Push to Google Cloud run


on:
    workflow_dispatch:
    push:
        branches:
            - "master"


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.8"
            - name: Install requirements
              run: |
                pip install --upgrade pip
                python -m pip install -r src/requirements.txt
            - name: Run tests
              env:
                MODE: "github actions"
              run: |
                pytest src/tests.py

    build_deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v2'
              with: 
                credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
            - name: Build container image
              run: |
                docker build -f Dockerfile -t inline-docker-tag .
                docker tag inline-docker-tag ${{ secrets.CONTAINER_IMAGE_URL }}:latest
                docker tag inline-docker-tag ${{ secrets.CONTAINER_IMAGE_URL }}:v1
                gcloud auth configure-docker ${{ secrets.GCLOUD_REGION }}-docker.pkg.dev
                docker push ${{ secrets.CONTAINER_IMAGE_URL }} --all-tags
            - name: Deploy container to cloud Run
              run: |
                gcloud run deploy ud-serverless-py-run \
                 --image=${{ secrets.CONTAINER_IMAGE_URL }}:latest \ 
                 --allow-unauthenticated \
                 --region=${{ secrets.GCLOUD_REGION }}\
                 --project=${{ secrets.GCLOUD_PROJECT_ID }}

